### ISSUE TITLE
Hyperparameters of the best interaction prediction model

### ISSUE THREAD

**Issue by WahabF** [MCZhi/GameFormer#9]
What are the hyperparameters used for the best model on the Waymo Interaction Prediction challenge?
The one reported to have a minADE of 0.9161.

There are some discrepancies between the default code values and the ones reported in the paper appendix. 
For example, do you consider 20 or 32 neighbors in the preprocessing code for the best results? 

Also if you can share the model weights that would be very useful. Thanks :)

**Comment by MCZhi** [comment]
Hi, @WahabF, thank you for your questions. The hyperparameters we use are given in the code. For interaction prediction, we take into account 32 neighbors, as indicated in the values of the preprocessing code. It is important to remind you that the values for open-loop planning and interaction prediction are different. Additioinally, due to the constraints of the Waymo dataset, we are unable to share the trained model. Please let us know if you have any further questions or concerns.
